# Generated by Django 4.0 on 2021-12-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='pizza_type',
            field=models.IntegerField(choices=[(1, 'Meat'), (2, 'Vegeterian'), (3, 'Vegan')], default=1),
        ),
    ]
