# Generated by Django 4.0 on 2021-12-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_pizza_pizza_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('user', 'pizza'), name='unique_like'),
        ),
    ]
